name: Plumeria Mathematics CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-darwin-m1:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        ./BuildScripts/install-pluscilib.sh darwin-m1
        ln -s openblas/cblas.h cblas.h
        ln -s openblas/lapack.h lapack.h
        swift build -v
    - name: Run tests
      run: swift test -v

  build-linux-aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        ./BuildScripts/install-pluscilib.sh linux-aarch64
        swift build -v
    - name: Run tests 
      run: swift test -v
