name: Plumeria Mathematics CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/bmurakami/plumeria-mathematics:latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and Test
      run: |
        . "/root/.local/share/swiftly/env.sh"
        source spack-installations.sh
        swift build -v
        swift test -v
