name: Plumeria Mathematics CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bmurakami/plumeria-mathematics:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    steps:
    - uses: actions/checkout@v4
    - name: Build and Test
      shell: bash
      run: |
        . /opt/spack/share/spack/setup-env.sh
        spack load openblas
        . /root/.local/share/swiftly/env.sh
        echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        swift package dump-package
        swift build -v
        swift test -v